export type Localization = {
    greeting: string,
    your: string,
    language: string,
    currentLocation: string,
    currentLanguage: string,
    changeLanguage: string,
    changeLocation: string,
    changeToLocation: string,
    currentlyInLocation: string,
    pickNewOne: string,
    whichNewLocation: string,
    noLocation: string,
    tryAgain: string,
    weather: string,
    temperature: string,
    precipitation: string,
    yes: string,
    no: string,
    reload: string,
    backToProfile: string,
    unknownLanguage: string,
};